version: '3'

services:
  frontend:
    image: bilalbadar01/frontend-image:5988bc2682d41bb2406126d14f436a2ceb9889e2
    ports:
      - "3000:3000"
    networks:
      - doc-app-network
  myappointment:
    image: bilalbadar01/appointment-image:5988bc2682d41bb2406126d14f436a2ceb9889e2
    ports:
      - "7070:7070"
    networks:
      - doc-app-network

  doctor:
    image: bilalbadar01/doctor-image:5988bc2682d41bb2406126d14f436a2ceb9889e2
    ports:
      - "9090:9090"
    networks:
      - doc-app-network

networks:
  doc-app-network:
    driver: bridge