version: '3'

services:
  frontend:
    image: bilalbadar01/frontend-image:6dc539356d674a1e2fa45eada73a198488aed51d
    ports:
      - "3000:3000"
    networks:
      - doc-app-network

  myappointment:
    image: bilalbadar01/appointment-image:6dc539356d674a1e2fa45eada73a198488aed51d
    ports:
      - "7070:7070"
    networks:
      - doc-app-network

  doctor:
    image: bilalbadar01/doctor-image:76802d5ad04e623139af93a336410740e2441c69
    ports:
      - "9090:9090"
    networks:
      - doc-app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

networks:
  doc-app-network:
    driver: bridge
