version: '3'

services:
  frontend:
    image: bilalbadar01/frontend-image:latest  
    ports:
      - "3000:3000"
    networks:
      - doc-app-network
  myappointment:
    image: bilalbadar01/appointment-image:795bf05081bd8f26e2b84b088e38227da1bb1af4
    ports:
      - "7070:7070"
    networks:
      - doc-app-network

  doctor:
    image: bilalbadar01/doctor-image:fc51d16eb8431e2d1acd361d036c3cb50b1731e9 
    ports:
      - "9090:9090"
    networks:
      - doc-app-network

networks:
  doc-app-network:
    driver: bridge