version: '3'

services:
  appointments:
    image: bilalbadar01/appointment-image:beec25731855d438d2174936068766a724d2fcca
    ports:
      - "7070:7070"
    environment:
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - doc_app_network

  doctors:
    image: bilalbadar01/doctor-image:fee89f838e3689d3e50ce19d6e414bff9c8ac31d
    ports:
      - "9090:9090"
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090 
    networks:
      - doc_app_network

  frontend:
    image: bilalbadar01/frontend-image:fee89f838e3689d3e50ce19d6e414bff9c8ac31d
    ports:
      - "3000:3000" 
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    depends_on:
      - doctors
      - appointments
    networks:
      - doc_app_network
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    networks:
      - doc_app_network
networks:
  doc_app_network:
    driver: bridge