version: '3'

services:
  frontend:
    image: bilalbadar01/frontend-image:28062dbbfef494b97ed5957423bf08f297054256
    ports:
      - "3000:3000"
    networks:
      - doc-app-network
  myappointment:
    image: bilalbadar01/appointment-image:f8c06e5f2bf1812cd42c224a86ad81a00e30ca05
    ports:
      - "7070:7070"
    networks:
      - doc-app-network

  doctor:
    image: bilalbadar01/doctor-image:c51faed960bac4bdc6e020af5a0685dd025e953d
    ports:
      - "9090:9090"
    networks:
      - doc-app-network

networks:
  doc-app-network:
    driver: bridge