version: '3'

services:
  frontend:
    image: bilalbadar01/frontend-image:28062dbbfef494b97ed5957423bf08f297054256
    ports:
      - "3000:3000"
    networks:
      - doc-app-network
  myappointment:
    image: bilalbadar01/appointment-image:c38339b53c7d475b5f4b34f50ff330bfca99c917
    ports:
      - "7070:7070"
    networks:
      - doc-app-network

  doctor:
    image: bilalbadar01/doctor-image:c38339b53c7d475b5f4b34f50ff330bfca99c917
    ports:
      - "9090:9090"
    networks:
      - doc-app-network

networks:
  doc-app-network:
    driver: bridge