apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments-container
        image: bilalbadar01/appointment-image:latest
        ports:
        - containerPort: 7070
        resources:
          limits:
            cpu: "0.5" 
            memory: "256Mi" 
        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070



