apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors
        image: bilalbadar01/doctor-image:beec25731855d438d2174936068766a724d2fcca
        ports:
        - containerPort: 9090
        env:
        - name: DOCTORS_SERVICE_URL
          value: "doctors:9090"
        resources:
          limits:
            cpu: '250m'
            memory: "64Mi"
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
