name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine changed paths
      id: changed_paths
      run: echo "::set-output name=paths::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

    - name: Build and push Doctors microservice
      if: contains(steps.changed_paths.outputs.paths, 'doctors/')
      run: |
        docker build -t bilalbadar01/doctor-image:${{ github.sha }} -t bilalbadar01/doctor-image:latest -f ./doctors/Dockerfile ./doctors
        docker push bilalbadar01/doctor-image:${{ github.sha }}
        docker push bilalbadar01/doctor-image:latest

    - name: Build and push Appointments microservice
      if: contains(steps.changed_paths.outputs.paths, 'appointments/')
      run: |
        docker build -t bilalbadar01/appointment-image:${{ github.sha }} -t bilalbadar01/appointment-image:latest -f ./appointments/Dockerfile ./appointments
        docker push bilalbadar01/appointment-image:${{ github.sha }}
        docker push bilalbadar01/appointment-image:latest

    - name: Build and push Frontend microservice
      if: contains(steps.changed_paths.outputs.paths, 'frontend/')
      run: |
        docker build -t bilalbadar01/frontend-image:${{ github.sha }} -t bilalbadar01/frontend-image:latest -f ./frontend/Dockerfile ./frontend
        docker push bilalbadar01/frontend-image:${{ github.sha }}
        docker push bilalbadar01/frontend-image:latest
