name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Doctors microservice
      run: |
        docker build -t bilalbadar01/doctor-image:${{ github.sha }} -t bilalbadar01/doctor-image:latest -f ./doctors/Dockerfile ./doctors
        docker push bilalbadar01/doctor-image:${{ github.sha }}
        docker push bilalbadar01/doctor-image:latest

    - name: Build and push Appointments microservice
      run: |
        docker build -t bilalbadar01/appointment-image:${{ github.sha }} -t bilalbadar01/appointment-image:latest -f ./appointments/Dockerfile ./appointments
        docker push bilalbadar01/appointment-image:${{ github.sha }}
        docker push bilalbadar01/appointment-image:latest

    - name: Build and push Frontend microservice
      run: |
        docker build -t bilalbadar01/frontend-image:${{ github.sha }} -t bilalbadar01/frontend-image:latest -f ./frontend/Dockerfile ./frontend
        docker push bilalbadar01/frontend-image:${{ github.sha }}
        docker push bilalbadar01/frontend-image:latest
    - name: Display head commit details
      run: |
          echo "Commit SHA: ${{ github.event.head_commit.id }}"
          echo "Author: ${{ github.event.head_commit.author.name }}"
          echo "Timestamp: ${{ github.event.head_commit.timestamp }}"
          echo "Message: ${{ github.event.head_commit.message }}"