name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
      paths:
        - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**' 

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display and Store Changed Files
      run: |
        git fetch --prune --unshallow
        CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD)
        echo "CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Set Git user identity
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend microservice
      run: |
        docker build -t bilalbadar01/frontend-image:${{ github.sha }} -t bilalbadar01/frontend-image:latest -f ./frontend/Dockerfile ./frontend
        docker push bilalbadar01/frontend-image:${{ github.sha }}
        docker push bilalbadar01/frontend-image:latest

        # Update Docker Compose file for Frontend microservice
        sed -i 's|bilalbadar01/frontend-image:.*|bilalbadar01/frontend-image:'"${{ github.sha }}"'|' docker-compose.yml
        git add docker-compose.yml
        git commit -m "Update Frontend microservice image tag to ${GITHUB_SHA}"
        git pull origin main --no-rebase
        git push 
