name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display and Store Changed Files
      run: |
        git fetch --prune --unshallow
        CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD)
        echo "Changed files: $CHANGED_FILES"
        echo "CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Doctors microservice
      run: |
        if echo "$CHANGED_FILES" | grep -qE "\bdoctors\b"; then
          docker build -t bilalbadar01/doctor-image:${{ github.sha }} -t bilalbadar01/doctor-image:latest -f ./doctors/Dockerfile ./doctors
          docker push bilalbadar01/doctor-image:${{ github.sha }}
          docker push bilalbadar01/doctor-image:latest
        fi

    - name: Build and push Appointments microservice
      run: |
        if echo "$CHANGED_FILES" | grep -qE "\appointments\b"; then
          docker build -t bilalbadar01/appointment-image:${{ github.sha }} -t bilalbadar01/appointment-image:latest -f ./appointments/Dockerfile ./appointments
          docker push bilalbadar01/appointment-image:${{ github.sha }}
          docker push bilalbadar01/appointment-image:latest
        fi

    - name: Build and push Frontend microservice
      run: |
        if echo "$CHANGED_FILES" | grep -qE "\bfrontend\b"; then
          docker build -t bilalbadar01/frontend-image:${{ github.sha }} -t bilalbadar01/frontend-image:latest -f ./frontend/Dockerfile ./frontend
          docker push bilalbadar01/frontend-image:${{ github.sha }}
          docker push bilalbadar01/frontend-image:latest
        fi
