name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Display changed files
      run: |
        echo "Changed files:"
        echo "${{ join(github.event.head_commit.modified, ', ') }}"