name: CI/CD Frontend

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend microservice
        run: |
          docker build -t bilalbadar01/frontend-image:${{ github.sha }} -t bilalbadar01/frontend-image:latest -f ./frontend/Dockerfile ./frontend
          docker push bilalbadar01/frontend-image:${{ github.sha }}

          # Update Docker Compose file for Frontend microservice
          sed -i 's|bilalbadar01/frontend-image:.*|bilalbadar01/frontend-image:'"${{ github.sha }}"'|' docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update Frontend microservice image tag to ${GITHUB_SHA}"
          git pull origin main --no-rebase
          git push
