name: Display Changed Files

on:
  push:
    branches:
      - main

jobs:
  display-changed-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Modified Files
      run: |
       echo "Before: ${{ github.event.before }}"
       echo "After: ${{ github.sha }}"
    - name: Get Modified Files
      run: |
        MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "Changed files: $MODIFIED_FILES"